LG-40116: Update documentation for Sdl.Terminology.TerminologyProvider.Core (Terminology public API)
RWS/studio-api-docs pull request #192
Opened 2023-10-27 11:54 UTC by paul-petrehus

2023-11-02 07:37 UTC, apetre2023 requested changes

2023-11-02 07:37 UTC, apetre2023 commented on apiconcepts/releasenotes/tradosstudio2022sr2.md
> +* Is no longer extented by interfaces `IConnectionAwareTerminologyProvider`, `ITerminologyProvider` and `IDisposable`
```suggestion
* Is no longer extended by interfaces `IConnectionAwareTerminologyProvider`, `ITerminologyProvider` and `IDisposable`
```

2023-11-02 07:37 UTC, apetre2023 commented on apiconcepts/releasenotes/tradosstudio2022sr2.md
> +* Added method `GetFilters()` to get all the filters definitions availabe for the terminology provider, it returns *IList<[FilterDefinition](../../api/terminology/Sdl.Terminology.TerminologyProvider.
```suggestion
* Added method `GetFilters()` to get all the filters definitions available for the terminology provider, it returns *IList<[FilterDefinition](../../api/terminology/Sdl.Terminology.TerminologyProvider.Core.FilterDefinition.yml)>*.
```

2023-11-02 07:37 UTC, apetre2023 commented on apiconcepts/releasenotes/tradosstudio2022sr2.md
> +* Added method `Uninitialize()` to be uninitialize the terminology provider, it returns a `boolean` value.
```suggestion
* Added method `Uninitialize()` to be used to uninitialize the terminology provider, it returns a `boolean` value.
```

2023-11-02 07:37 UTC, apetre2023 commented on apiconcepts/releasenotes/tradosstudio2022sr2.md
> +* Added property `IsEditing { get; }` used to indicate wether the component TerminologyProviderViewerWinFormsUI is in edit mode, it returns a `boolean` value.
```suggestion
* Added property `IsEditing { get; }` used to indicate whether the component TerminologyProviderViewerWinFormsUI is in edit mode, it returns a `boolean` value.
```

2023-11-02 07:37 UTC, apetre2023 commented on apiconcepts/releasenotes/tradosstudio2022sr2.md
> +* Has method [Edit(IWin32Window owner, ITerminologyProvider terminologyProvider)](../../api/terminology/Sdl.Terminology.TerminologyProvider.Core.ITerminologyProviderWinFormsUIWithEdit.yml#Sdl_Termino
```suggestion
* Has method [Edit(IWin32Window owner, ITerminologyProvider terminologyProvider)](../../api/terminology/Sdl.Terminology.TerminologyProvider.Core.ITerminologyProviderWinFormsUIWithEdit.yml#Sdl_Terminology_TerminologyProvider_Core_ITerminologyProviderWinFormsUIWithEdit_Edit_System_Windows_Forms_IWin32Window_Sdl_Terminology_TerminologyProvider_Core_ITerminologyProvider_) used to display a dialog to interactively change any of the terminology provider settings.
```

2023-11-03 12:02 UTC, caiaandrei approved these changes

2023-11-03 12:05 UTC, apetre2023 approved these changes

2023-11-03 12:08 UTC, merged